name: caldor
description: Library for generating FieldKit calibration data.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.5

dependencies:
  data: ^0.12.0
  protobuf: ^3.1.0
  fixnum: ^1.0.1
  fk_data_protocol:
    git:
      url: https://gitlab.com/fieldkit/libraries/data-protocol.git
      ref: 5db13c9c986f4f6a69b24aca7024bd55f07f8110
      path: dart

dev_dependencies:
  lib: ^0.0.3
  lints: ^3.0.0
  test: ^1.21.0
